/**
 * NOAA-OWP Snow17 + LGAR GPU Kernels — REAL DATA harness
 *
 * Copy of water-prediction/owp_snow17_lgar.cu with the synthetic data
 * generators (gen_snow_data / gen_lgar_data) replaced by loaders for real
 * NOAA-OWP datasets. Kernel math and CPU reference implementations are copied
 * VERBATIM from the original and unchanged.
 *
 * Real data:
 *  1. Snow17 — NOAA-OWP/snow17 test_cases/ex1: South Fork Flathead River above
 *     Hungry Horse reservoir, MT; two elevation bands (HHWM8IL/HHWM8IU) with
 *     real calibrated parameters and 16,801 daily P/T records (1970-2015).
 *     State (we, liqw, neghs, aesc, tprev) trajectories are generated by
 *     running the UNTOUCHED CPU reference sequentially over the real series
 *     from a cold start; batches tile the resulting 33,602 real
 *     (state, params, forcing) tuples.
 *  2. LGAR (Green-Ampt variant) — NOAA-OWP/LGAR-C: Phillipsburg, KS and
 *     Bushland, TX sites; top-layer van Genuchten-derived parameters and
 *     8,760 real hourly precipitation records each (water years 2017/2021).
 *     Cumulative-infiltration state trajectories from the UNTOUCHED CPU
 *     reference (cold start, dt = 3600 s); 17,520 real tuples.
 *
 * Prep: prep_snow17.py, prep_lgar.py  (see headers for provenance)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <cuda_runtime.h>

// ============================================================
// KERNEL 1: Snow17 — Simplified single-period snow model    (verbatim)
// Based on PACK19 from NOAA-OWP/snow17
// ============================================================

struct Snow17State {
    float we;       // water equivalent (mm)
    float liqw;     // liquid water in snowpack (mm)
    float neghs;    // heat deficit (mm)
    float accmax;   // max accumulation (mm)
    float aesc;     // areal extent of snow cover (0-1)
    float tprev;    // previous temperature
};

struct Snow17Params {
    float scf;      // snow correction factor
    float mfmax;    // max melt factor (mm/degC/6hr)
    float mfmin;    // min melt factor
    float uadj;     // wind function adjustment
    float si;       // mean areal water equivalent for 100% cover (mm)
    float tipm;     // antecedent temperature index parameter
    float mbase;    // base temperature for melt (degC)
    float plwhc;    // percent liquid water holding capacity
    float daygm;    // daily ground melt (mm/day)
    float pxtemp;   // rain/snow discriminator temperature (degC)
};

struct Snow17Forcing {
    float ta;       // air temperature (degC)
    float px;       // precipitation (mm)
};

// CPU reference — simplified Snow17 single period
void cpu_snow17(
    Snow17State* state,
    const Snow17Params* params,
    const Snow17Forcing* forcing,
    float* runoff_out,
    float dt_hours,
    int ncatch)
{
    for (int c = 0; c < ncatch; c++) {
        float ta = forcing[c].ta;
        float px = forcing[c].px;
        float we = state[c].we;
        float liqw = state[c].liqw;
        float neghs = state[c].neghs;
        float tprev = state[c].tprev;

        float scf = params[c].scf;
        float mbase = params[c].mbase;
        float plwhc = params[c].plwhc;
        float daygm = params[c].daygm;
        float pxtemp = params[c].pxtemp;
        float tipm = params[c].tipm;
        float mfmax = params[c].mfmax;
        float si = params[c].si;

        // Antecedent temperature index
        float ati = tprev + tipm * (ta - tprev);

        // Precipitation form (rain/snow)
        float frac_snow = (ta < pxtemp) ? 1.0f : 0.0f;
        if (ta >= pxtemp && ta < pxtemp + 2.0f)
            frac_snow = 1.0f - (ta - pxtemp) / 2.0f;

        float sfall = px * frac_snow * scf;
        float rain = px * (1.0f - frac_snow);

        // Snow accumulation
        we += sfall;

        // Melt calculation
        float melt = 0.0f;
        if (we > 0.0f && ta > mbase) {
            // Temperature index melt
            float mf = mfmax; // simplified — full model varies by day of year
            melt = mf * (ta - mbase);
            if (melt > we) melt = we;

            // Rain-on-snow melt
            if (rain > 0.0f && ta > 0.0f) {
                // Stefan-Boltzmann + vapor pressure
                float tak = (ta + 273.0f) * 0.01f;
                float tak4 = tak * tak * tak * tak;
                float sbci = 6.12e-10f; // Stefan-Boltzmann / (24*dt)
                float qn = sbci * (tak4 - 55.55f);

                // Vapor pressure
                float ea = 2.7489e8f * expf(-4278.63f / (ta + 242.792f));
                ea *= 0.9f;

                float rainm = 0.0125f * rain * ta; // rain melt contribution
                melt += rainm;
            }
        }

        // Areal extent
        float aesc = (we > 0.0f) ? fminf(1.0f, we / si) : 0.0f;
        melt *= aesc;

        // Heat deficit
        if (ta < 0.0f && we > 0.0f) {
            float heat = -ta * 0.5f; // simplified heat loss
            neghs += heat;
        }

        // Water balance
        float water = melt + rain;
        float liqwmx = plwhc * we;
        float excess = 0.0f;

        if (neghs > 0.0f && water > 0.0f) {
            float used = fminf(water, neghs);
            neghs -= used;
            water -= used;
        }

        liqw += water;
        we -= melt;
        if (we < 0.0f) we = 0.0f;

        if (liqw > liqwmx) {
            excess = liqw - liqwmx;
            liqw = liqwmx;
        }

        // Ground melt
        float robg = daygm * dt_hours / 24.0f;

        runoff_out[c] = excess + robg;

        state[c].we = we;
        state[c].liqw = liqw;
        state[c].neghs = neghs;
        state[c].aesc = aesc;
        state[c].tprev = ati;
    }
}

// GPU kernel
__global__ void kernel_snow17(
    Snow17State* __restrict__ state,
    const Snow17Params* __restrict__ params,
    const Snow17Forcing* __restrict__ forcing,
    float* __restrict__ runoff_out,
    float dt_hours,
    int ncatch)
{
    int c = blockIdx.x * blockDim.x + threadIdx.x;
    if (c >= ncatch) return;

    float ta = forcing[c].ta;
    float px = forcing[c].px;
    float we = state[c].we;
    float liqw = state[c].liqw;
    float neghs = state[c].neghs;
    float tprev = state[c].tprev;

    float scf = params[c].scf;
    float mbase = params[c].mbase;
    float plwhc = params[c].plwhc;
    float daygm = params[c].daygm;
    float pxtemp = params[c].pxtemp;
    float tipm = params[c].tipm;
    float mfmax = params[c].mfmax;
    float si = params[c].si;

    float ati = tprev + tipm * (ta - tprev);

    float frac_snow = (ta < pxtemp) ? 1.0f : 0.0f;
    if (ta >= pxtemp && ta < pxtemp + 2.0f)
        frac_snow = 1.0f - (ta - pxtemp) / 2.0f;

    float sfall = px * frac_snow * scf;
    float rain = px * (1.0f - frac_snow);

    we += sfall;

    float melt = 0.0f;
    if (we > 0.0f && ta > mbase) {
        float mf = mfmax;
        melt = mf * (ta - mbase);
        if (melt > we) melt = we;

        if (rain > 0.0f && ta > 0.0f) {
            float tak = (ta + 273.0f) * 0.01f;
            float tak4 = tak * tak * tak * tak;
            float ea = 2.7489e8f * __expf(-4278.63f / (ta + 242.792f));
            ea *= 0.9f;
            float rainm = 0.0125f * rain * ta;
            melt += rainm;
        }
    }

    float aesc = (we > 0.0f) ? fminf(1.0f, we / si) : 0.0f;
    melt *= aesc;

    if (ta < 0.0f && we > 0.0f) {
        neghs += -ta * 0.5f;
    }

    float water = melt + rain;
    float liqwmx = plwhc * we;

    if (neghs > 0.0f && water > 0.0f) {
        float used = fminf(water, neghs);
        neghs -= used;
        water -= used;
    }

    liqw += water;
    we -= melt;
    if (we < 0.0f) we = 0.0f;

    float excess = 0.0f;
    if (liqw > liqwmx) {
        excess = liqw - liqwmx;
        liqw = liqwmx;
    }

    float robg = daygm * dt_hours / 24.0f;
    runoff_out[c] = excess + robg;

    state[c].we = we;
    state[c].liqw = liqw;
    state[c].neghs = neghs;
    state[c].aesc = aesc;
    state[c].tprev = ati;
}

// ============================================================
// KERNEL 2: LGAR Infiltration (Green-Ampt variant)   (verbatim)
// Simplified from NOAA-OWP/LGAR-C
// ============================================================

struct LGARParams {
    float Ks;          // saturated hydraulic conductivity (m/s)
    float porosity;    // soil porosity
    float wetting_front_suction; // wetting front suction head (m)
    float initial_moisture;      // initial soil moisture
    float soil_depth;            // total soil depth (m)
};

// CPU reference
void cpu_lgar(
    const LGARParams* params,
    const float* precip_rate,  // precipitation rate (m/s) [ncatch]
    float* infiltration_out,   // infiltration rate (m/s) [ncatch]
    float* runoff_out,         // surface runoff (m/s) [ncatch]
    float* cum_infil,          // cumulative infiltration (m) [ncatch, in/out]
    float dt,
    int ncatch)
{
    for (int c = 0; c < ncatch; c++) {
        float Ks = params[c].Ks;
        float psi = params[c].wetting_front_suction;
        float theta_d = params[c].porosity - params[c].initial_moisture;
        float F = cum_infil[c];

        // Green-Ampt infiltration capacity
        float f_cap;
        if (F > 0.0f) {
            f_cap = Ks * (1.0f + psi * theta_d / F);
        } else {
            f_cap = precip_rate[c]; // all infiltrates initially
        }

        // Actual infiltration
        float f_actual = fminf(precip_rate[c], f_cap);

        // Check soil capacity
        float max_infil = params[c].soil_depth * theta_d;
        if (F + f_actual * dt > max_infil) {
            f_actual = fmaxf(0.0f, (max_infil - F) / dt);
        }

        infiltration_out[c] = f_actual;
        runoff_out[c] = fmaxf(0.0f, precip_rate[c] - f_actual);
        cum_infil[c] = F + f_actual * dt;
    }
}

// GPU kernel
__global__ void kernel_lgar(
    const LGARParams* __restrict__ params,
    const float* __restrict__ precip_rate,
    float* __restrict__ infiltration_out,
    float* __restrict__ runoff_out,
    float* __restrict__ cum_infil,
    float dt,
    int ncatch)
{
    int c = blockIdx.x * blockDim.x + threadIdx.x;
    if (c >= ncatch) return;

    float Ks = params[c].Ks;
    float psi = params[c].wetting_front_suction;
    float theta_d = params[c].porosity - params[c].initial_moisture;
    float F = cum_infil[c];

    float f_cap = (F > 0.0f) ? Ks * (1.0f + psi * theta_d / F) : precip_rate[c];
    float f_actual = fminf(precip_rate[c], f_cap);

    float max_infil = params[c].soil_depth * theta_d;
    if (F + f_actual * dt > max_infil) {
        f_actual = fmaxf(0.0f, (max_infil - F) / dt);
    }

    infiltration_out[c] = f_actual;
    runoff_out[c] = fmaxf(0.0f, precip_rate[c] - f_actual);
    cum_infil[c] = F + f_actual * dt;
}

// ============================================================
// REAL DATA loading (replaces synthetic generators)
// ============================================================

static void die(const char* msg) { fprintf(stderr, "FATAL: %s\n", msg); exit(1); }

#define SNOW_DT_HOURS 24.0f   // daily timestep of the HHWM8 ex1 case study
#define LGAR_DT 3600.0f       // hourly forcing resolution per LASAM configs

// ---- Snow17: real HHWM8 params/forcing + CPU-reference state trajectory ----
typedef struct {
    int nlib;
    Snow17State*   state;     // [nlib] state BEFORE the step
    Snow17Params*  params;    // [nlib]
    Snow17Forcing* forcing;   // [nlib]
} SnowLibrary;

static SnowLibrary g_snow;

void load_snow_library(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) die("cannot open snow17_realdata.bin (run prep_snow17.py)");
    int magic, nhru, nrec;
    if (fread(&magic, 4, 1, f) != 1 || magic != 0x534E4F57) die("snow magic");
    fread(&nhru, 4, 1, f);
    fread(&nrec, 4, 1, f);

    Snow17Params* ps = (Snow17Params*)malloc(nhru * sizeof(Snow17Params));
    for (int h = 0; h < nhru; h++) {
        float v[10];
        fread(v, 4, 10, f);
        ps[h].scf = v[0]; ps[h].mfmax = v[1]; ps[h].mfmin = v[2]; ps[h].uadj = v[3];
        ps[h].si = v[4]; ps[h].tipm = v[5]; ps[h].mbase = v[6]; ps[h].plwhc = v[7];
        ps[h].daygm = v[8]; ps[h].pxtemp = v[9];
    }
    float* forc = (float*)malloc((size_t)nhru * nrec * 2 * 4);
    fread(forc, 4, (size_t)nhru * nrec * 2, f);
    fclose(f);

    g_snow.nlib = nhru * nrec;
    g_snow.state = (Snow17State*)malloc((size_t)g_snow.nlib * sizeof(Snow17State));
    g_snow.params = (Snow17Params*)malloc((size_t)g_snow.nlib * sizeof(Snow17Params));
    g_snow.forcing = (Snow17Forcing*)malloc((size_t)g_snow.nlib * sizeof(Snow17Forcing));

    // sequential drive with the untouched CPU reference (cold start per HRU)
    for (int h = 0; h < nhru; h++) {
        Snow17State st;
        memset(&st, 0, sizeof(st));
        for (int t = 0; t < nrec; t++) {
            int idx = h * nrec + t;
            Snow17Forcing fz;
            fz.ta = forc[((size_t)h * nrec + t) * 2 + 0];
            fz.px = forc[((size_t)h * nrec + t) * 2 + 1];
            g_snow.state[idx] = st;          // pre-step state
            g_snow.params[idx] = ps[h];
            g_snow.forcing[idx] = fz;
            float runoff;
            cpu_snow17(&st, &ps[h], &fz, &runoff, SNOW_DT_HOURS, 1);
        }
    }
    printf("[data] Snow17 library: %d real (state,forcing) tuples (%d HRUs x %d days, "
           "HHWM8 1970-2015)\n", g_snow.nlib, nhru, nrec);
    free(ps); free(forc);
}

void fill_snow_batch(Snow17State* st, Snow17Params* p, Snow17Forcing* fz, int nc) {
    for (int c = 0; c < nc; c++) {
        int s = c % g_snow.nlib;
        st[c] = g_snow.state[s];
        p[c] = g_snow.params[s];
        fz[c] = g_snow.forcing[s];
    }
}

// ---- LGAR: real site params/forcing + CPU-reference cumulative-infiltration ----
typedef struct {
    int nlib;
    LGARParams* params;   // [nlib]
    float* precip;        // [nlib] m/s
    float* cum0;          // [nlib] pre-step cumulative infiltration (m)
} LgarLibrary;

static LgarLibrary g_lgar;

void load_lgar_library(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) die("cannot open lgar_realdata.bin (run prep_lgar.py)");
    int magic, nsite;
    if (fread(&magic, 4, 1, f) != 1 || magic != 0x4C474152) die("lgar magic");
    fread(&nsite, 4, 1, f);

    // first pass: read everything
    LGARParams* sp = (LGARParams*)malloc(nsite * sizeof(LGARParams));
    float** series = (float**)malloc(nsite * sizeof(float*));
    int* nrec = (int*)malloc(nsite * sizeof(int));
    int total = 0;
    for (int s = 0; s < nsite; s++) {
        float v[5];
        fread(v, 4, 5, f);
        sp[s].Ks = v[0]; sp[s].porosity = v[1]; sp[s].wetting_front_suction = v[2];
        sp[s].initial_moisture = v[3]; sp[s].soil_depth = v[4];
        fread(&nrec[s], 4, 1, f);
        series[s] = (float*)malloc((size_t)nrec[s] * 4);
        fread(series[s], 4, nrec[s], f);
        total += nrec[s];
    }
    fclose(f);

    g_lgar.nlib = total;
    g_lgar.params = (LGARParams*)malloc((size_t)total * sizeof(LGARParams));
    g_lgar.precip = (float*)malloc((size_t)total * 4);
    g_lgar.cum0 = (float*)malloc((size_t)total * 4);

    int idx = 0;
    for (int s = 0; s < nsite; s++) {
        float F = 0.0f;   // cold start
        for (int t = 0; t < nrec[s]; t++) {
            g_lgar.params[idx] = sp[s];
            g_lgar.precip[idx] = series[s][t];
            g_lgar.cum0[idx] = F;             // pre-step state
            float fi, ro;
            cpu_lgar(&sp[s], &series[s][t], &fi, &ro, &F, LGAR_DT, 1);
            idx++;
        }
        free(series[s]);
    }
    printf("[data] LGAR library: %d real (state,forcing) tuples (%d sites x 8760 h, "
           "Phillipsburg WY2017 + Bushland WY2021)\n", g_lgar.nlib, nsite);
    free(sp); free(series); free(nrec);
}

void fill_lgar_batch(LGARParams* p, float* precip, float* cum, int nc) {
    for (int c = 0; c < nc; c++) {
        int s = c % g_lgar.nlib;
        p[c] = g_lgar.params[s];
        precip[c] = g_lgar.precip[s];
        cum[c] = g_lgar.cum0[s];
    }
}

// ============================================================
// Benchmarks  (structure as original; data source swapped)
// ============================================================

void bench_snow17(int ncatch) {
    printf("--- Snow17 (REAL HHWM8 data): %d catchments ---\n", ncatch);

    Snow17State *hs=(Snow17State*)malloc((size_t)ncatch*sizeof(Snow17State));
    Snow17State *hs_gpu=(Snow17State*)malloc((size_t)ncatch*sizeof(Snow17State));
    Snow17Params *hp=(Snow17Params*)malloc((size_t)ncatch*sizeof(Snow17Params));
    Snow17Forcing *hf=(Snow17Forcing*)malloc((size_t)ncatch*sizeof(Snow17Forcing));
    float *hr_cpu=(float*)malloc((size_t)ncatch*4), *hr_gpu=(float*)malloc((size_t)ncatch*4);

    fill_snow_batch(hs, hp, hf, ncatch);   // REAL DATA (was gen_snow_data)
    memcpy(hs_gpu, hs, (size_t)ncatch*sizeof(Snow17State));

    clock_t t0=clock();
    cpu_snow17(hs, hp, hf, hr_cpu, SNOW_DT_HOURS, ncatch);
    double cpu_ms=1000.0*(clock()-t0)/(double)CLOCKS_PER_SEC;

    Snow17State *ds; Snow17Params *dp; Snow17Forcing *df; float *dr;
    cudaMalloc(&ds, (size_t)ncatch*sizeof(Snow17State));
    cudaMalloc(&dp, (size_t)ncatch*sizeof(Snow17Params));
    cudaMalloc(&df, (size_t)ncatch*sizeof(Snow17Forcing));
    cudaMalloc(&dr, (size_t)ncatch*4);
    cudaMemcpy(dp, hp, (size_t)ncatch*sizeof(Snow17Params), cudaMemcpyHostToDevice);
    cudaMemcpy(df, hf, (size_t)ncatch*sizeof(Snow17Forcing), cudaMemcpyHostToDevice);

    int thr=256, blk=(ncatch+thr-1)/thr;

    // Warmup
    cudaMemcpy(ds, hs_gpu, (size_t)ncatch*sizeof(Snow17State), cudaMemcpyHostToDevice);
    kernel_snow17<<<blk,thr>>>(ds, dp, df, dr, SNOW_DT_HOURS, ncatch);
    cudaDeviceSynchronize();

    cudaEvent_t e0,e1; cudaEventCreate(&e0); cudaEventCreate(&e1);
    int runs=50;
    cudaEventRecord(e0);
    for(int r=0;r<runs;r++){
        cudaMemcpy(ds, hs_gpu, (size_t)ncatch*sizeof(Snow17State), cudaMemcpyHostToDevice);
        kernel_snow17<<<blk,thr>>>(ds, dp, df, dr, SNOW_DT_HOURS, ncatch);
    }
    cudaEventRecord(e1); cudaEventSynchronize(e1);
    float gpu_ms; cudaEventElapsedTime(&gpu_ms,e0,e1); gpu_ms/=runs;

    // Get results with fresh state
    cudaMemcpy(ds, hs_gpu, (size_t)ncatch*sizeof(Snow17State), cudaMemcpyHostToDevice);
    kernel_snow17<<<blk,thr>>>(ds, dp, df, dr, SNOW_DT_HOURS, ncatch);
    cudaMemcpy(hr_gpu, dr, (size_t)ncatch*4, cudaMemcpyDeviceToHost);

    float max_abs=0, max_rel=0; int nan_c=0, fail_c=0;
    for(int c=0;c<ncatch;c++){
        if(isnan(hr_gpu[c])){nan_c++;continue;}
        float ae=fabsf(hr_gpu[c]-hr_cpu[c]);
        if(ae>max_abs)max_abs=ae;
        if(fabsf(hr_cpu[c])>1e-10f){
            float re=ae/fabsf(hr_cpu[c]);
            if(re>max_rel)max_rel=re;
            if(re>1e-4f)fail_c++;
        }
    }

    printf("  CPU: %.1f ms | GPU: %.3f ms | Speedup: %.1fx\n", cpu_ms, gpu_ms, cpu_ms/gpu_ms);
    printf("  Max abs: %.2e | Max rel: %.2e | NaN: %d | >0.01%% err: %d/%d\n",
           max_abs, max_rel, nan_c, fail_c, ncatch);
    printf("  Status: %s\n\n",
           (nan_c==0&&max_rel<1e-4f)?"PASS":(nan_c==0&&max_rel<1e-2f)?"PASS (fast exp)":"NEEDS REVIEW");

    free(hs);free(hs_gpu);free(hp);free(hf);free(hr_cpu);free(hr_gpu);
    cudaFree(ds);cudaFree(dp);cudaFree(df);cudaFree(dr);
    cudaEventDestroy(e0);cudaEventDestroy(e1);
}

void bench_lgar(int ncatch) {
    printf("--- LGAR Infiltration (REAL LASAM data): %d catchments ---\n", ncatch);

    LGARParams *hp=(LGARParams*)malloc((size_t)ncatch*sizeof(LGARParams));
    float *hprecip=(float*)malloc((size_t)ncatch*4);
    float *hcum_cpu=(float*)malloc((size_t)ncatch*4), *hcum_gpu=(float*)malloc((size_t)ncatch*4);
    float *hinf_cpu=(float*)malloc((size_t)ncatch*4), *hinf_gpu=(float*)malloc((size_t)ncatch*4);
    float *hro_cpu=(float*)malloc((size_t)ncatch*4), *hro_gpu=(float*)malloc((size_t)ncatch*4);

    fill_lgar_batch(hp, hprecip, hcum_cpu, ncatch);   // REAL DATA (was gen_lgar_data)
    memcpy(hcum_gpu, hcum_cpu, (size_t)ncatch*4);

    float dt = LGAR_DT; // 1 h, real forcing resolution

    clock_t t0=clock();
    cpu_lgar(hp, hprecip, hinf_cpu, hro_cpu, hcum_cpu, dt, ncatch);
    double cpu_ms=1000.0*(clock()-t0)/(double)CLOCKS_PER_SEC;

    LGARParams *dp; float *dprecip, *dcum, *dinf, *dro;
    cudaMalloc(&dp, (size_t)ncatch*sizeof(LGARParams));
    cudaMalloc(&dprecip, (size_t)ncatch*4); cudaMalloc(&dcum, (size_t)ncatch*4);
    cudaMalloc(&dinf, (size_t)ncatch*4); cudaMalloc(&dro, (size_t)ncatch*4);
    cudaMemcpy(dp, hp, (size_t)ncatch*sizeof(LGARParams), cudaMemcpyHostToDevice);
    cudaMemcpy(dprecip, hprecip, (size_t)ncatch*4, cudaMemcpyHostToDevice);

    int thr=256, blk=(ncatch+thr-1)/thr;

    cudaMemcpy(dcum, hcum_gpu, (size_t)ncatch*4, cudaMemcpyHostToDevice);
    kernel_lgar<<<blk,thr>>>(dp, dprecip, dinf, dro, dcum, dt, ncatch);
    cudaDeviceSynchronize();

    cudaEvent_t e0,e1; cudaEventCreate(&e0); cudaEventCreate(&e1);
    int runs=50;
    cudaEventRecord(e0);
    for(int r=0;r<runs;r++){
        cudaMemcpy(dcum, hcum_gpu, (size_t)ncatch*4, cudaMemcpyHostToDevice);
        kernel_lgar<<<blk,thr>>>(dp, dprecip, dinf, dro, dcum, dt, ncatch);
    }
    cudaEventRecord(e1); cudaEventSynchronize(e1);
    float gpu_ms; cudaEventElapsedTime(&gpu_ms,e0,e1); gpu_ms/=runs;

    cudaMemcpy(dcum, hcum_gpu, (size_t)ncatch*4, cudaMemcpyHostToDevice);
    kernel_lgar<<<blk,thr>>>(dp, dprecip, dinf, dro, dcum, dt, ncatch);
    cudaMemcpy(hinf_gpu, dinf, (size_t)ncatch*4, cudaMemcpyDeviceToHost);

    float max_abs=0, max_rel=0; int nan_c=0;
    for(int c=0;c<ncatch;c++){
        if(isnan(hinf_gpu[c])){nan_c++;continue;}
        float ae=fabsf(hinf_gpu[c]-hinf_cpu[c]);
        if(ae>max_abs)max_abs=ae;
        if(fabsf(hinf_cpu[c])>1e-15f){
            float re=ae/fabsf(hinf_cpu[c]);
            if(re>max_rel)max_rel=re;
        }
    }

    printf("  CPU: %.1f ms | GPU: %.3f ms | Speedup: %.1fx\n", cpu_ms, gpu_ms, cpu_ms/gpu_ms);
    printf("  Max abs: %.2e | Max rel: %.2e | NaN: %d\n", max_abs, max_rel, nan_c);
    printf("  Status: %s\n\n",
           (nan_c==0&&max_rel<1e-5f)?"PASS":(nan_c==0&&max_rel<1e-3f)?"PASS (FP32 rounding)":"NEEDS REVIEW");

    free(hp);free(hprecip);free(hcum_cpu);free(hcum_gpu);
    free(hinf_cpu);free(hinf_gpu);free(hro_cpu);free(hro_gpu);
    cudaFree(dp);cudaFree(dprecip);cudaFree(dcum);cudaFree(dinf);cudaFree(dro);
    cudaEventDestroy(e0);cudaEventDestroy(e1);
}

int main(int argc, char** argv) {
    const char* snow_path = (argc > 1) ? argv[1] : "data/snow17_realdata.bin";
    const char* lgar_path = (argc > 2) ? argv[2] : "data/lgar_realdata.bin";

    printf("================================================\n");
    printf("  NOAA-OWP Snow17 + LGAR GPU Kernels — REAL DATA\n");
    printf("  HHWM8 (Flathead R.) + LASAM (Phillipsburg/Bushland)\n");
    printf("  RTX 5070 12GB (sm_120)\n");
    printf("================================================\n\n");

    load_snow_library(snow_path);
    load_lgar_library(lgar_path);
    printf("\n");

    printf("========== SNOW17 ==========\n\n");
    bench_snow17(33602);    // pure real tuples, no replication
    bench_snow17(100000);
    bench_snow17(1000000);
    bench_snow17(2700000);

    printf("========== LGAR INFILTRATION ==========\n\n");
    bench_lgar(17520);      // pure real tuples, no replication
    bench_lgar(100000);
    bench_lgar(1000000);
    bench_lgar(2700000);

    return 0;
}
